### ISSUE TITLE
Hey, Just a heads up.

### ISSUE THREAD

**Issue by NopeNotDark** [MakerbakerYT/CryticOpFactins#1]
### This message is a forward of NopeNotDark's Content.

> You have to go test it in the server, there are more errors inside of it nice to see someone go into it!

**Comment by MakerbakerYT** [comment]
Thank You Also I Am Testing it on a server and ters an error wit kits and base loader

**Comment by NopeNotDark** [comment]
### This message is a forward of NopeNotDark's Content.

> Put your name in the plugin.yml, As Modified Or Modded So They Know you fixed it.

**Comment by MakerbakerYT** [comment]
So like what do i change on it?

**Comment by NopeNotDark** [comment]
Like
`name: CrypticFactions
author: [Modded] MakerBakerYT
main: core\Cryptic
load: POSTWORLD
version: "1.0.0"
api: 3.0.0
description: A OP factions core for CrypticPE.`

**Comment by MakerbakerYT** [comment]
Oh okie Thank u

**Comment by NopeNotDark** [comment]
-  [x] Update Plugin.yml
